baseurl: /

profile:
  name: David Charte
  alias: fdavidcl
  pic: https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200
  links:
    Blog: http://blog.fdavidcl.me
    Github: https://github.com/fdavidcl
    Twitter: https://twitter.com/fdavidcl
    LinkedIn: https://linkedin.com/in/fdavidcl
    Scholar: https://scholar.google.es/citations?user=FRv_MwYAAAAJ

style:
  background: "ffffff"
  foreground: "000000"
  accent: "00bcd4"
  font: "Source Sans Pro"

# This list helps the index page show the correct collections in the desired order
lists:
  - research
  - projects

permalink: pretty

markdown: kramdown
kramdown:
  parse_span_html: false
highlighter: rouge

# This list tells Jekyll which collections exist
collections:
  - research
  - projects
