baseurl: ""

profile:
  name: David Charte
  alias: fdavidcl
  pic: https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200
  links:
    Twitter:
      url: https://twitter.com/fdavidcl
      icon: twitter
    Instagram:
      url: https://instagram.com/fdavidcl
      icon: instagram
    Github:
      url: https://github.com/fdavidcl
      icon: github-circled
    LinkedIn:
      url: https://linkedin.com/in/fdavidcl
      icon: linkedin-squared
    ResearchGate:
      url: https://www.researchgate.net/profile/David_Charte
      icon: graduation-cap

style:
  background: "ffffff"
  foreground: "000000"
  accent: "00bcd4"
  font: "Source Sans Pro"
  monofont: "Inconsolata"

# This list helps the index page show the correct collections in the desired order
side:
  tags:
    - research
    - projects

# Settings for the blog section
enable_blog: true
plugins:
  - octopress-paginate
#  - jekyll-minifier

exclude:
  - Gemfile
  - vendor

defaults:
  - values:
      lang: es
      layout: post

permalink: pretty

markdown: kramdown
kramdown:
  parse_span_html: false
highlighter: rouge

tag_dir: "/tag"
tag_title_prefix: "Tag '"
tag_title_suffix: "'"
