baseurl: /

profile:
  name: David Charte
  alias: fdavidcl
  pic: https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200
  links:
    Github: https://github.com/fdavidcl
    Blog: http://blog.fdavidcl.me
    Twitter: https://twitter.com/fdavidcl
    LinkedIn: https://linkedin.com/in/fdavidcl
    Scholar: https://scholar.google.es/citations?user=FRv_MwYAAAAJ

collections:
  - publications
  - projects
