baseurl: /

profile:
  name: David Charte
  alias: fdavidcl
  pic: https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200
  links:
    Blog:
      url: http://blog.fdavidcl.me
      icon: rss
    Github:
      url: https://github.com/fdavidcl
      icon: github
    Twitter:
      url: https://twitter.com/fdavidcl
      icon: twitter
    LinkedIn:
      url: https://linkedin.com/in/fdavidcl
      icon: linkedin
    Scholar:
      url: https://scholar.google.es/citations?user=FRv_MwYAAAAJ
      icon: graduation-cap

style:
  background: "ffffff"
  foreground: "000000"
  accent: "00bcd4"
  font: "Source Sans Pro"

# This list helps the index page show the correct collections in the desired order
lists:
  - research
  - projects

# This list tells Jekyll which collections exist
collections:
  research:
    output: true
  projects:

# Settings for the blog section
enable_blog: true
gems:
  - octopress-paginate

exclude:
  - Gemfile

defaults:
  - values:
      lang: es
      layout: post

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  parse_span_html: false
highlighter: rouge
